jobs:
  include:
    - name: "Go"
      language: go
      env:
        - GO111MODULE=on
      script: go test -v ./go/...

    - name: "Specifications"
      language: python

      python:
        - "3.7"

      addons:
        apt:
          packages:
           - xsltproc

      env:
        global:
         - GOPATH="${TRAVIS_BUILD_DIR}/.go_workspace"
         - mmark_src=github.com/miekg/mmark/mmark
         - mmark=./mmark

      install:
       - pip install bikeshed
       - bikeshed update
       - pip install xml2rfc
       - if head -1 -q *.md | grep '^\-\-\-' >/dev/null 2>&1; then gem install --no-doc kramdown-rfc2629; fi
       - if head -1 -q *.md | grep '^%%%' >/dev/null 2>&1; then go get "$mmark_src" && go build "$mmark_src"; fi

      script:
       - bikeshed --die-on=warning spec loading.bs
       - make
       - make issues || make issues DISABLE_ISSUE_FETCH=true && make gh-issues
       - make gh-pages

      deploy:
        provider: script
        script: make upload
        skip_cleanup: true
        on:
          tags: true
