language: python
sudo: false
dist: trusty

python:
  - "2.7"

addons:
  apt:
    packages:
     - python-pip
     - xsltproc

env:
  global:
   - GOPATH="${TRAVIS_BUILD_DIR}/.go_workspace"
   - mmark_src=github.com/miekg/mmark/mmark
   - mmark=./mmark

install:
 - git clone --depth=1 https://github.com/tabatkins/bikeshed.git
 - pip install --editable bikeshed
 - bikeshed update
 - pip install xml2rfc!=2.15.0
 - if head -1 -q *.md | grep '^\-\-\-' >/dev/null 2>&1; then gem install --no-doc kramdown-rfc2629; fi
 - if head -1 -q *.md | grep '^%%%' >/dev/null 2>&1; then go get "$mmark_src" && go build "$mmark_src"; fi

script:
 - bikeshed spec loading.bs
 - make
 - make issues || make issues DISABLE_ISSUE_FETCH=true && make gh-issues
 - make gh-pages

deploy:
  provider: script
  script: make upload
  skip_cleanup: true
  on:
    tags: true
