name: build
on: [push, pull_request]
jobs:
  go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.16.6"
      - run: go test -v ./go/...

  js-wbn:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12, 14, 16]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm --prefix ./js/bundle ci
      - run: npm --prefix ./js/bundle run build
      - run: npm --prefix ./js/bundle test

  js-wbn-sign:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14, 16]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm --prefix ./js/sign ci
      - run: npm --prefix ./js/sign run build
      - run: npm --prefix ./js/sign test

  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: creyD/prettier_action@v4.2
        with:
          prettier_options: --write **/*.{js,ts}
          only_changed: True
          dry: True
          prettier_version: 2.7.1
